import React, { useState } from 'react';
import './EngineeringGraphicsFlashcards.css';

const EngineeringGraphicsFlashcards = () => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);

  const flashcards = [
    { question: "What is the first angle projection method?", answer: "In the first angle projection, the object is placed in the first quadrant, and the projections are drawn on the planes behind and below the object." },
    { question: "What is the difference between first and third angle projection?", answer: "In the first angle, the object is between the observer and the projection plane. In the third angle, the projection plane is between the observer and the object." },
    { question: "What is an isometric projection?", answer: "An isometric projection is a method of visually representing three-dimensional objects in two dimensions, where the axes are equally inclined at 120°." },
    { question: "Define orthographic projection.", answer: "Orthographic projection is a way of drawing an object from multiple views (top, front, side) using perpendicular projectors from the object to the projection planes." },
    { question: "What are the standard views in engineering drawings?", answer: "The standard views are Front View, Top View (Plan), and Side View (Elevation)." },
    { question: "How is a section view used in drawings?", answer: "A section view shows the internal features of an object by cutting through it along a plane, revealing hidden details." },
    { question: "What is the scale of a drawing?", answer: "The scale is the ratio of the size of the object in the drawing to its actual size, such as 1:1, 1:2, or 2:1." },
    { question: "Explain the concept of dimensioning.", answer: "Dimensioning involves adding measurements and notes to a drawing to provide clear instructions for manufacturing or construction." },
    { question: "What is the purpose of a title block?", answer: "A title block contains essential information about the drawing, including title, scale, date, name of the drafter, and company details." },
    { question: "What are the different types of lines used in technical drawings?", answer: "Types of lines include visible lines, hidden lines, center lines, dimension lines, extension lines, and cutting plane lines." },
    { question: "What is perspective projection?", answer: "Perspective projection represents an object as it appears to the human eye, with objects farther away appearing smaller." },
    { question: "Define tolerance in engineering graphics.", answer: "Tolerance specifies the permissible variation in a dimension, ensuring parts fit and function correctly." },
    { question: "What is the purpose of a Bill of Materials (BOM)?", answer: "A BOM lists all the materials, parts, and components needed to manufacture a product, along with quantities and specifications." },
    { question: "What is a CAD system?", answer: "CAD (Computer-Aided Design) systems are software tools used to create, modify, analyze, or optimize engineering drawings." },
    { question: "What is the function of center lines in a drawing?", answer: "Center lines indicate the axes of symmetry or paths of rotation in a component." },
    { question: "What is the function of section lining in a sectional view?", answer: "Section lining (hatching) represents the material of the cut object and differentiates it from other parts." },
    { question: "What are the three principal planes of projection?", answer: "The three principal planes are the Horizontal Plane (HP), Vertical Plane (VP), and Profile Plane (PP)." },
    { question: "What is the purpose of auxiliary views?", answer: "Auxiliary views are used to show features that are not parallel to the principal planes, providing a true shape of inclined surfaces." },
    { question: "What is the difference between a detail drawing and an assembly drawing?", answer: "A detail drawing shows a single part with all dimensions, while an assembly drawing shows how parts fit together in a complete product." },
    { question: "What is the function of hidden lines in a drawing?", answer: "Hidden lines represent edges or features not visible in the current view." },
    { question: "What is meant by freehand sketching?", answer: "Freehand sketching is drawing without instruments, used for quick, rough representations of ideas or components." },
    { question: "What is a Pictorial Drawing?", answer: "A pictorial drawing shows an object in three dimensions as it appears to the observer, commonly using isometric or perspective projections." },
    { question: "What is the role of a section line (cutting plane line)?", answer: "It indicates where the object is cut to create a sectional view." },
    { question: "What is a helix in engineering graphics?", answer: "A helix is a three-dimensional curve generated by a point moving around a cylinder or cone while advancing along its axis." },
    { question: "What is a chamfer?", answer: "A chamfer is a beveled edge connecting two surfaces, often used to remove sharp edges or ease assembly." },
    { question: "What is a fillet in engineering graphics?", answer: "A fillet is a rounded corner or edge on a part, often added to reduce stress concentration." },
    { question: "What is the purpose of exploded views in assembly drawings?", answer: "Exploded views show how parts fit together by illustrating them spread out in their relative positions." },
    { question: "What is a locus in engineering graphics?", answer: "A locus is a path traced by a point moving according to a specific condition or rule, such as a circle or ellipse." },
    { question: "What is the difference between a bolt and a screw?", answer: "Bolts are used with nuts, while screws are threaded directly into the material." },
    { question: "What is the purpose of a thread profile?", answer: "The thread profile defines the shape and size of threads, ensuring compatibility and function." },
    { question: "What is a spline in technical drawing?", answer: "A spline is a smooth curve that passes through or near a series of points, used to represent complex shapes." },
    { question: "What is the significance of a keyway?", answer: "A keyway is a slot or recess in a shaft and hub, used to transmit torque in mechanical assemblies." },
    { question: "What is a datum in engineering drawings?", answer: "A datum is a reference point, line, or surface from which dimensions are measured." },
    { question: "What is the purpose of toleranced dimensions?", answer: "Toleranced dimensions specify the acceptable limits of variation in a measurement, ensuring parts fit together properly." },
    { question: "What are GD&T symbols?", answer: "Geometric Dimensioning and Tolerancing (GD&T) symbols define the allowable variations in the shape and position of a part." },
    { question: "What is the role of a break line in technical drawings?", answer: "Break lines indicate that a portion of the drawing has been removed for clarity or to save space." },
    { question: "What is the difference between a flat and a round key?", answer: "Flat keys are rectangular, while round keys are circular; both are used for transmitting torque in shafts." },
    { question: "What is the importance of assembly constraints in CAD?", answer: "Assembly constraints control the relative position and motion of components in a CAD assembly model." },
    { question: "What is a blueprint?", answer: "A blueprint is a detailed technical drawing used as a guide for manufacturing or construction." },
    { question: "What are the different types of CAD modeling?", answer: "Types include wireframe modeling, surface modeling, and solid modeling." },
    { question: "What is a perspective view used for?", answer: "Perspective views are used to represent an object as it appears to the eye, adding depth and realism to the drawing." },
    { question: "What is the purpose of an exploded view in CAD?", answer: "An exploded view shows all components of an assembly spaced apart to illustrate their relationships and assembly sequence." },
    { question: "What is a section modulus?", answer: "The section modulus is a measure of the strength of a cross-section in bending, calculated as Z = I/c, where I is the moment of inertia and c is the distance to the outermost fiber." },
  ];

  const handleNext = () => {
    setIsFlipped(false);
    setCurrentIndex((prevIndex) => 
      prevIndex === flashcards.length - 1 ? 0 : prevIndex + 1
    );
  };

  const handlePrevious = () => {
    setIsFlipped(false);
    setCurrentIndex((prevIndex) => 
      prevIndex === 0 ? flashcards.length - 1 : prevIndex - 1
    );
  };

  const handleFlip = () => {
    setIsFlipped(!isFlipped);
  };

  return (
    <div className="flashcards-container">
      <h1>Engineering Graphics Flashcards</h1>
      <p>Click on the card to flip it and reveal the answer.</p>

      <div className="card-scene">
        <div 
          className={`card ${isFlipped ? 'is-flipped' : ''}`} 
          onClick={handleFlip}
        >
          <div className="card__face card__face--front">
            {flashcards[currentIndex].question}
          </div>
          <div className="card__face card__face--back">
            {flashcards[currentIndex].answer}
          </div>
        </div>
      </div>

      <div className="navigation-buttons">
        <button onClick={handlePrevious}>Previous</button>
        <button onClick={handleFlip}>Flip</button>
        <button onClick={handleNext}>Next</button>
      </div>

      <div className="progress">
        {currentIndex + 1} / {flashcards.length}
      </div>
    </div>
  );
};

export default EngineeringGraphicsFlashcards;
